version: '3'

services:
  pocketspace:
    build: .
    image: pocketspace
    container_name: pocketspace
    volumes:
      - ./src/:/home/pocketspace/
    restart: unless-stopped
    stdin_open: true
